### ISSUE TITLE
Why Lupyne?

### ISSUE THREAD

**Issue by seperman** [coady/lupyne#2]
Hello,

While looking around for how to run PyLucene, I stumbled around your docker image for PyLucene and eventually here. I'm curious why you have written Lupyne? Is it to provide a more Pythonic interface to Lucene? Why should one use Lupyne over PyLucene? The lack of documentation on PyLucene makes me feel like only a handful of people are actually using PyLucene...

Thanks,
Sep

**Comment by coady** [comment]
>  Is it to provide a more Pythonic interface to Lucene?

Yes, that's the primary motivation.  The [examples](https://lupyne.surge.sh/examples.html) contrast the lucene api with lupyne.

I'm not sure about PyLucene's usage either, especially since it's not pip installable, so no pypi download stats.
