### ISSUE TITLE
ImportError: cannot import name 'spans' from 'org.apache.lucene.search' (unknown location)

### ISSUE THREAD

**Issue by gklpcsgn** [coady/lupyne#21]
I'm using coady/pylucene:latest docker file and trying to import from lupyne import engine. But it gives me this error. 

`Traceback (most recent call last):
  File "/opt/project/main.py", line 1, in <module>
    from lupyne import engine
  File "/usr/local/lib/python3.11/site-packages/lupyne/engine/__init__.py", line 10, in <module>
    from .queries import Query  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lupyne/engine/queries.py", line 6, in <module>
    from org.apache.lucene.search import spans
ImportError: cannot import name 'spans' from 'org.apache.lucene.search' (unknown location)`

**Comment by coady** [comment]
The last release only supports PyLucene 8; try `coady/pylucene:8`.

I've had trouble getting tests to pass - that is not core dump - under PyLucene 9, so I'm not sure about the future of this project. But the `main` branch should support PyLucene 9.1 if you want to give it a try.

**Comment by gklpcsgn** [comment]
I tried with `coady/pylucene:8`.
Now I get this error.

_Traceback (most recent call last):
  File "/opt/project/main.py", line 14, in <module>
    analyzer = analysis.standard.StandardAnalyzer(util.Version.LUCENE_CURRENT)
lucene.InvalidArgsError: (<class 'org.apache.lucene.analysis.standard.StandardAnalyzer'>, '__init__', (<Version: 8.11.0>,))_

**Comment by coady** [comment]
That error isn't in `lupyne`. [StandardAnalyzer](https://lucene.apache.org/core/8_11_0/core/org/apache/lucene/analysis/standard/StandardAnalyzer.html) doesn't take a version argument (it used to).

**Comment by coady** [comment]
Just released `v3.0` which supports PyLucene 9.
